### ISSUE TITLE
Plugin can not load correctly

### ISSUE THREAD

**Issue by YKDZ** [WolfyScript/CustomCrafting#152]
### What happened?

This error will appear when plugin load.

### How can the bug be reproduced?

no

### Expected Behaviour?

no

### Plugin version

CustomCrafing 3.16.7.0 WolfyUtils 4.16.4.1

### Server software

Purpur 1.19

### Relevant log output

```shell
[15:39:34 INFO]: [CustomCrafting] Enabling CustomCrafting v3.16.7.0
[15:39:34 INFO]: [CustomCrafting] ____ _  _ ____ ___ ____ _  _ ____ ____ ____ ____ ___ _ _  _ ____
[15:39:34 INFO]: [CustomCrafting] |    |  | [__   |  |  | |\/| |    |__/ |__| |___  |  | |\ | | __
[15:39:34 INFO]: [CustomCrafting] |___ |__| ___]  |  |__| |  | |___ |  \ |  | |     |  | | \| |__]
[15:39:34 INFO]: [CustomCrafting]     Version    | v3.16.7.0
[15:39:34 INFO]: [CustomCrafting]     WolfyUtils | v4.16.4.1
[15:39:34 INFO]: [CustomCrafting]     Bukkit     | git-Purpur-1689 (MC: 1.19)(API: 1.19-R0.1-SNAPSHOT)
[15:39:34 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_19_R1! Trying to find NMS support
[15:39:34 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_19_R1' loaded!
[15:39:34 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[15:39:34 INFO]: [CustomCrafting]
[15:39:34 INFO]: [CustomCrafting] Special thanks to my Patrons for supporting this project:
[15:39:34 INFO]: [CustomCrafting] Omarlatif, Nat R, Junye Zhou, Apprehentice, PwassonDoDouce, Mr_Mint_
[15:39:34 INFO]: [CustomCrafting] ------------------------------------------------------------------------
[15:39:34 INFO]: [CustomCrafting] Loaded fallback language "en_US" v6.0.0 translated by WolfyScript
[15:39:34 INFO]: [CustomCrafting] Loaded active language "zh_CN" v6.0.0 translated by 肆零肆E
[15:39:34 INFO]: [CustomCrafting] Detected ProtocolLib... initiating additional features.
[15:39:34 INFO]: [CustomCrafting] 注册变量
[15:39:34 INFO]: [PlaceholderAPI] Successfully registered expansion: customcrafting [3.16.7.0]
[15:39:34 INFO]: [CustomCrafting] Data destination: LOCAL
[15:39:34 INFO]: [NBTAPI] [NBTAPI] The NBT-API seems to be up-to-date!
[15:39:34 INFO]: [CustomCrafting] 启动库存GUI
[15:39:34 INFO]: [CustomCrafting] Register ItemCreator Tabs
[15:39:35 ERROR]: Error occurred while enabling CustomCrafting v3.16.7.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.enchantments.Enchantment.getStartLevel()" because the return value of "org.bukkit.enchantments.EnchantmentWrapper.getEnchantment()" is null
        at org.bukkit.enchantments.EnchantmentWrapper.getStartLevel(EnchantmentWrapper.java:32) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.addEnchantment(ItemStack.java:410) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at me.wolfyscript.utilities.util.inventory.item_builder.AbstractItemBuilder.addEnchantment(AbstractItemBuilder.java:98) ~[wolfyutils-spigot-4.16.4.1.jar:?]
        at me.wolfyscript.customcrafting.gui.item_creator.ButtonArmorSlotToggle.<init>(ButtonArmorSlotToggle.java:49) ~[customcrafting-spigot-3_16_7_0.jar:?]
        at me.wolfyscript.customcrafting.gui.item_creator.tabs.TabArmorSlots.register(TabArmorSlots.java:50) ~[customcrafting-spigot-3_16_7_0.jar:?]
        at me.wolfyscript.customcrafting.gui.item_creator.MenuItemCreator.lambda$onInit$22(MenuItemCreator.java:172) ~[customcrafting-spigot-3_16_7_0.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at me.wolfyscript.customcrafting.gui.item_creator.MenuItemCreator.onInit(MenuItemCreator.java:172) ~[customcrafting-spigot-3_16_7_0.jar:?]
        at me.wolfyscript.utilities.api.inventory.gui.GuiCluster.registerGuiWindow(GuiCluster.java:105) ~[wolfyutils-spigot-4.16.4.1.jar:?]
        at me.wolfyscript.customcrafting.gui.item_creator.ClusterItemCreator.onInit(ClusterItemCreator.java:43) ~[customcrafting-spigot-3_16_7_0.jar:?]
        at me.wolfyscript.utilities.api.inventory.gui.InventoryAPI.registerCluster(InventoryAPI.java:74) ~[wolfyutils-spigot-4.16.4.1.jar:?]
        at me.wolfyscript.customcrafting.CustomCrafting.registerInventories(CustomCrafting.java:424) ~[customcrafting-spigot-3_16_7_0.jar:?]
        at me.wolfyscript.customcrafting.CustomCrafting.onEnable(CustomCrafting.java:322) ~[customcrafting-spigot-3_16_7_0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:597) ~[purpur-1.19.jar:git-Purpur-1689]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:511) ~[purpur-1.19.jar:git-Purpur-1689]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.jar:git-Purpur-1689]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1689]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1689]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1689]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1689]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by YKDZ** [comment]
After test, I think this error also caused by CMI. When remove CMI, this error will disapear. My CMI version is 9.2.2.0 (newest up to now)
