### ISSUE TITLE
most CustomCrafting commands not functioning correctly and old recipes not loading

### ISSUE THREAD

**Issue by BookWyrm114** [WolfyScript/CustomCrafting#189]
### What happened?

Customcrafting isn't working at all as of the latest update, it loads but /cc, /recipes, etc. no longer work (/reload still works but does nothing to help the issue), and all my recipes that I already had no longer load, and ofc I can't make new ones. It may be an issue with Purpur since I saw no errors from CustomCrafting relating to another plugin, nor errors any other plugin relating to customcrafting. Also, WolfyUtilities seems to function perfectly with no errors, only CustomCrafting has an issue. If you need a full server log I'm happy to upload one, but for now I included all error messages I received and organized them in the "relevant log output" section

### How can the bug be reproduced?

Install the latest version of CustomCrafting and WolfyUtilities, and start the server.

### Expected Behaviour?

For recipes and the plugin to load correct;y

### Plugin version

CustomCrafting 4.16.3.0, Wolfy Utilities 4.16.6.1

### Server software

Purpur build #1845

### Relevant log output

```shell
All startup errors:
=========================================================================
[16:50:10 INFO]: [CustomCrafting] Loading CustomCrafting v4.16.3.0
[16:50:10 INFO]: [CustomCrafting] WolfyUtils API: v4.16.7.0
[16:50:10 INFO]: [CustomCrafting] CustomCrafting: v4.16.3.0
[16:50:10 INFO]: [CustomCrafting] Environment : PROD
[16:50:10 INFO]: [CustomCrafting] Registering CustomItem Data
[16:50:10 ERROR]: [org.bukkit.craftbukkit.v1_19_R1.CraftServer] 'me.wolfyscript.utilities.registry.TypeRegistry me.wolfyscript.utilities.registry.Registries.getCustomItemDataTypeRegistry()' initializing CustomCrafting v4.16.3.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'me.wolfyscript.utilities.registry.TypeRegistry me.wolfyscript.utilities.registry.Registries.getCustomItemDataTypeRegistry()'
at me.wolfyscript.customcrafting.CustomCrafting.onLoad(CustomCrafting.java:254) ~[customcrafting-spigot-4.16.3.0.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:475) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1845]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
=========================================================================
[16:51:04 INFO]: [CustomCrafting] Enabling CustomCrafting v4.16.3.0
[16:51:04 INFO]: [CustomCrafting] ____ _ _ ____ ___ ____ _ _ ____ ____ ____ ____ ___ _ _ _ ____
[16:51:04 INFO]: [CustomCrafting] | | | [__ | | | |\/| | |__/ |__| |___ | | |\ | | __
[16:51:04 INFO]: [CustomCrafting] |___ |__| ___] | |__| | | |___ | \ | | | | | | \| |__]
[16:51:04 INFO]: [CustomCrafting] Version | v4.16.3.0
[16:51:04 INFO]: [CustomCrafting] WolfyUtils | v4.16.7.0
[16:51:04 INFO]: [CustomCrafting] Bukkit | git-Purpur-1845 (MC: 1.19.2)(API: 1.19.2-R0.1-SNAPSHOT)
[16:51:04 INFO]: [CustomCrafting]
[16:51:04 INFO]: [CustomCrafting] Special thanks to my Patrons for supporting this project:
[16:51:04 INFO]: [CustomCrafting] Omarlatif, Nat R, Junye Zhou, Apprehentice, PwassonDoDouce, Mr_Mint_
[16:51:04 INFO]: [CustomCrafting] ------------------------------------------------------------------------
[16:51:04 INFO]: [CustomCrafting] Loaded fallback language "en_US" v6.1.0 translated by WolfyScript
[16:51:04 INFO]: [CustomCrafting] Loaded active language "en_US" v6.1.0 translated by WolfyScript
[16:51:05 INFO]: [CustomCrafting] Detected ProtocolLib... initiating additional features.
[16:51:05 INFO]: [CustomCrafting] Registering PlaceHolder
[16:51:05 INFO]: [PlaceholderAPI] Successfully registered expansion: customcrafting [4.16.3.0]
[16:51:05 INFO]: [CustomCrafting] Data destination: LOCAL
[16:51:05 ERROR]: [CustomCrafting] Plugin CustomCrafting v4.16.3.0 has failed to register events for class me.wolfyscript.customcrafting.listeners.EliteWorkbenchListener because com/wolfyscript/utilities/bukkit/items/CustomItemData does not exist.
[16:51:05 INFO]: [CustomCrafting] Initiating Inventory GUIs
[16:51:05 INFO]: [CustomCrafting] Register ItemCreator Tabs
[16:51:06 INFO]: [CustomCrafting] ------------------------------------------------------------------------
=========================================================================
[16:51:14 INFO]: [WolfyUtilities] Dependencies Loaded. Calling DependenciesLoadedEvent!
[16:51:14 INFO]: [CustomCrafting] ------------------------------------------------------------------------
[16:51:14 INFO]: [CustomCrafting] Loading Recipes & Items
[16:51:14 INFO]: [CustomCrafting] - - - - [Local Storage] - - - -
[16:51:14 INFO]: [CustomCrafting] [LOCAL] Looking through data folder...
[16:51:14 INFO]: [CustomCrafting] [LOCAL] Loading Items
[16:51:14 INFO]: [CustomCrafting] [LOCAL] Loading Recipes
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:customcrafting/advanced_crafting_table": Could not resolve type id 'customcrafting:crafting_shaped' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:customcrafting/recipe_book": Could not resolve type id 'customcrafting:crafting_shapeless' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:diorite/basketweave_diorite_bricks": Could not resolve type id 'customcrafting:stonecutter' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:diorite/bonded_diorite_bricks": Could not resolve type id 'customcrafting:stonecutter' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:diorite/cut_diorite": Could not resolve type id 'customcrafting:stonecutter' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:diorite/diorite_bricks": Could not resolve type id 'customcrafting:stonecutter' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:diorite/diorite_double_slabs": Could not resolve type id 'customcrafting:stonecutter' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:diorite/diorite_herningbone_bricks": Could not resolve type id 'customcrafting:stonecutter' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:diorite/diorite_small_bricks": Could not resolve type id 'customcrafting:stonecutter' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:diorite/diorite_square_bricks": Could not resolve type id 'customcrafting:stonecutter' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:diorite/polished_cut_diorite": Could not resolve type id 'customcrafting:stonecutter' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:diorite/polished_cut_diorite2": Could not resolve type id 'customcrafting:stonecutter' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:warden_extended/warden_bone_boots": Could not resolve type id 'customcrafting:crafting_shaped' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:warden_extended/warden_bone_chestplate": Could not resolve type id 'customcrafting:crafting_shaped' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:warden_extended/warden_bone_helmet_1": Could not resolve type id 'customcrafting:crafting_shaped' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:warden_extended/warden_bone_helmet_2": Could not resolve type id 'customcrafting:crafting_shaped' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:warden_extended/warden_bone_leggings": Could not resolve type id 'customcrafting:crafting_shaped' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:zombies/compressed_flesh": Could not resolve type id 'customcrafting:crafting_shapeless' as a subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe`: Class `java.lang.Object` not subtype of `me.wolfyscript.customcrafting.recipes.CustomRecipe` at [Source: (String); line: 1]
[16:51:15 INFO]: [CustomCrafting] [LOCAL] Loaded 0 recipes; Skipped: 18 error/s, 0 already existing
[16:51:15 INFO]: [CustomCrafting] [LOCAL_OLD] Loaded 0 recipes; Skipped: 0 error/s, 0 already existing
[16:51:15 INFO]: [CustomCrafting] [LOCAL_LEGACY] Loaded 0 recipes; Skipped: 0 error/s, 0 already existing
[16:51:15 INFO]: [CustomCrafting] [LOCAL] Loaded 0 recipes
[16:51:15 INFO]: [CustomCrafting]
[16:51:15 INFO]: [CustomCrafting] Indexing Recipe Book...
[16:51:15 INFO]: [CustomCrafting] Indexed Recipe Book!
[16:51:15 INFO]: [CustomCrafting] ------------------------------------------------------------------------
=========================================================================
errors from trying to execute a command:
=========================================================================
[16:53:50 INFO]: BookWyrm_ issued server command: /cc
[16:53:50 WARN]: [CustomCrafting] Task #23577 for CustomCrafting v4.16.3.0 generated an exception
java.lang.NullPointerException: Cannot invoke "me.wolfyscript.customcrafting.data.CCPlayerData.getDarkBackground()" because "<local2>" is null
at me.wolfyscript.customcrafting.gui.CCWindow.onUpdateAsync(CCWindow.java:59) ~[customcrafting-spigot-4.16.3.0.jar:?]
at me.wolfyscript.customcrafting.gui.main_gui.MenuMain.onUpdateAsync(MenuMain.java:119) ~[customcrafting-spigot-4.16.3.0.jar:?]
at me.wolfyscript.utilities.api.inventory.gui.GuiWindow.openInventory(GuiWindow.java:282) ~[wolfyutils-spigot-4.16.7.0.jar:?]
at me.wolfyscript.utilities.api.inventory.gui.GuiWindow.lambda$callUpdate$1(GuiWindow.java:272) ~[wolfyutils-spigot-4.16.7.0.jar:?]
at me.wolfyscript.utilities.api.inventory.gui.GuiWindow.callUpdate(GuiWindow.java:274) ~[wolfyutils-spigot-4.16.7.0.jar:?]
at me.wolfyscript.utilities.api.inventory.gui.GuiWindow.lambda$update$0(GuiWindow.java:265) ~[wolfyutils-spigot-4.16.7.0.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1845]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1845]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
=========================================================================
[16:54:46 INFO]: BookWyrm_ issued server command: /recipes
[16:54:46 WARN]: [CustomCrafting] Task #30974 for CustomCrafting v4.16.3.0 generated an exception
java.lang.NullPointerException: Cannot invoke "me.wolfyscript.customcrafting.data.CCPlayerData.getDarkBackground()" because "<local2>" is null
at me.wolfyscript.customcrafting.gui.CCWindow.onUpdateAsync(CCWindow.java:59) ~[customcrafting-spigot-4.16.3.0.jar:?]
at me.wolfyscript.customcrafting.gui.recipebook.MenuMain.onUpdateAsync(MenuMain.java:66) ~[customcrafting-spigot-4.16.3.0.jar:?]
at me.wolfyscript.utilities.api.inventory.gui.GuiWindow.openInventory(GuiWindow.java:282) ~[wolfyutils-spigot-4.16.7.0.jar:?]
at me.wolfyscript.utilities.api.inventory.gui.GuiWindow.lambda$callUpdate$1(GuiWindow.java:272) ~[wolfyutils-spigot-4.16.7.0.jar:?]
at me.wolfyscript.utilities.api.inventory.gui.GuiWindow.callUpdate(GuiWindow.java:274) ~[wolfyutils-spigot-4.16.7.0.jar:?]
at me.wolfyscript.utilities.api.inventory.gui.GuiWindow.lambda$update$0(GuiWindow.java:265) ~[wolfyutils-spigot-4.16.7.0.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1845]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1845]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
=========================================================================
[16:55:23 INFO]: BookWyrm_ issued server command: /customcrafting darkmode
[16:55:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'customcrafting darkmode' in me.wolfyscript.customcrafting.commands.CommandCC(customcrafting)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1845]
at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1845]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1845]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1845]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.wolfyscript.customcrafting.data.CCPlayerData.isDarkMode()" because the return value of "me.wolfyscript.customcrafting.utils.PlayerUtil.getStore(org.bukkit.entity.Player)" is null
at me.wolfyscript.customcrafting.commands.cc_subcommands.DarkModeSubCommand.onCommand(DarkModeSubCommand.java:46) ~[customcrafting-spigot-4.16.3.0.jar:?]
at me.wolfyscript.customcrafting.commands.IndexCommand.execute(IndexCommand.java:59) ~[customcrafting-spigot-4.16.3.0.jar:?]
at me.wolfyscript.customcrafting.commands.CommandCC.execute(CommandCC.java:71) ~[customcrafting-spigot-4.16.3.0.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
... 22 more
=========================================================================
All other commands functioned without errors, however trying to give myself a recipe book or elite table said that the items didn't exist
=========================================================================
=========================================================================
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Make sure to get the latest WolfyUtilities version. 
The latest CC update requires at least WolfyUtilities v4.16.8.0

**Comment by BookWyrm114** [comment]
Oh, sorry, I just checked curseforge and it’s out there, but the version still hasn’t been updated on spigot. I’ll test again with that. Thank you! Also please update the version number on spigot if you can, I had no idea the new wolfyutilities was out, and other people may also have the same issue.

**Comment by BookWyrm114** [comment]
updating wolfyutilities worked but please do update the spigot page when wolfyutilities updates so users can more easily find new versions when they are released
