### ISSUE TITLE
Task #4420399 for CustomCrafting v4.16.8.5 generated an exception

### ISSUE THREAD

**Issue by DJcrafter5606** [WolfyScript/CustomCrafting#344]
### What happened?

Custom Crafting grid doesn't let ItemEdit items on the grid, those items just dissapear and this error appears. It seems it has to do with MythicMob custom item creation.

### How can the bug be reproduced?

Put unstackable items on the custom crafting grid to create a new craft or an ItemEdit created item

### Expected Behaviour?

Let you create a new craft

### Plugin version

Custom Crafting 4.16.8.5 // WolfyUtilies 4.16.15-beta5

### Server software

Paper 1.19.3

### Relevant log output

```shell
[CustomCrafting] Task #4468887 for CustomCrafting v4.16.8.5 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.setAmount(int)" because "stack" is null
        at me.wolfyscript.utilities.compatibility.plugins.mythicmobs.MythicMobsStackIdentifier.stack(MythicMobsStackIdentifier.java:34) ~[wolfyutils-spigot-4.16.15-beta.5.jar:?]
        at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.getItemStack(CustomItem.java:695) ~[wolfyutils-spigot-4.16.15-beta.5.jar:?]
        at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.<init>(CustomItem.java:185) ~[wolfyutils-spigot-4.16.15-beta.5.jar:?]
        at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.getReferenceByItemStack(CustomItem.java:367) ~[wolfyutils-spigot-4.16.15-beta.5.jar:?]
        at me.wolfyscript.customcrafting.gui.recipe_creator.ButtonRecipeIngredient.lambda$new$1(ButtonRecipeIngredient.java:59) ~[customcrafting-spigot-4.16.8.5.jar:?]
        at me.wolfyscript.utilities.api.inventory.gui.button.buttons.ActionButton.postExecute(ActionButton.java:145) ~[wolfyutils-spigot-4.16.15-beta.5.jar:?]
        at me.wolfyscript.utilities.api.inventory.gui.button.buttons.ItemInputButton.postExecute(ItemInputButton.java:98) ~[wolfyutils-spigot-4.16.15-beta.5.jar:?]
        at me.wolfyscript.utilities.api.inventory.gui.GuiUpdate.lambda$postExecuteButtons$0(GuiUpdate.java:202) ~[wolfyutils-spigot-4.16.15-beta.5.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at me.wolfyscript.utilities.api.inventory.gui.GuiUpdate.postExecuteButtons(GuiUpdate.java:200) ~[wolfyutils-spigot-4.16.15-beta.5.jar:?]
        at me.wolfyscript.utilities.api.inventory.gui.GuiWindow.lambda$update$0(GuiWindow.java:266) ~[wolfyutils-spigot-4.16.15-beta.5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
I uploaded a new version of WolfyUtils. v4.16.15-beta.6 on [Modrinth](https://modrinth.com/plugin/wolfyutils/version/4.16.15-beta.6) that should address this issue.

**Comment by SoraShiunin** [comment]
> I uploaded a new version of WolfyUtils. v4.16.15-beta.6 on [Modrinth](https://modrinth.com/plugin/wolfyutils/version/4.16.15-beta.6) that should fix this issue.

I'm having the same issue with Custom/mmoitems items disappearing, these types of items also disappeared from all my recipes T_T. Im on paper 1.20.4 and just tried that wolfyutils build but issue persists. No error in console that I could find.

https://github.com/WolfyScript/CustomCrafting/assets/23641964/6ec24221-ff57-4b84-bc47-304f7ff3f68a

**Comment by addpromax** [comment]
This bug still not be fix.
When mythicmobs install
