### ISSUE TITLE
Could not pass event PluginIntegrationEnableEvent to CustomCrafting v4.16.10

### ISSUE THREAD

**Issue by ShadySt** [WolfyScript/CustomCrafting#378]
### What happened?

I discovered that after updating to CustomCrafting v4.16.10 and setting sync: true in main config - ItemsAdder recipes are missing after server load.
If I reload plugin itself via /cc reload command - all recipes are loaded then.

Only error I found is this:
[11:40:25 INFO]: [WolfyUtilities] Enabled plugin integration for ItemsAdder
[11:40:25 ERROR]: Could not pass event PluginIntegrationEnableEvent to CustomCrafting v4.16.10
(Full log attached)

### How can the bug be reproduced?

Just install all mentioned plugins, create any recipe with ItemsAdder item and reload server.

### Expected Behaviour?

All recipes succesfully load on server start. 

### Plugin version

CustomCrafting v4.16.10, WolfyUtils 4.17-beta4, ItemsAdder_3.6.4-release-3

### Server software

Paper 1.20.4

### Relevant log output

```shell
[11:40:25 INFO]: [WolfyUtilities] Enabled plugin integration for ItemsAdder
[11:40:25 ERROR]: Could not pass event PluginIntegrationEnableEvent to CustomCrafting v4.16.10
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
        at com.google.common.collect.AbstractMapBasedMultimap$KeySet$1.next(AbstractMapBasedMultimap.java:964) ~[guava-32.1.2-jre.jar:?]
        at me.wolfyscript.customcrafting.handlers.LocalStorageLoader.validatePending(LocalStorageLoader.java:206) ~[customcrafting-spigot-4.16.10.jar:?]
        at me.wolfyscript.customcrafting.handlers.DataHandler.integrationEnable(DataHandler.java:150) ~[customcrafting-spigot-4.16.10.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-466]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-466]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-466]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.wolfyscript.utilities.compatibility.PluginIntegrationAbstract.enable(PluginIntegrationAbstract.java:108) ~[wolfyutils-spigot-4.17-beta.4.jar:?]
        at me.wolfyscript.utilities.compatibility.PluginIntegrationAbstract.markAsDoneLoading(PluginIntegrationAbstract.java:131) ~[wolfyutils-spigot-4.17-beta.4.jar:?]
        at me.wolfyscript.utilities.compatibility.plugins.itemsadder.ItemsAdderImpl.onLoaded(ItemsAdderImpl.java:65) ~[wolfyutils-spigot-4.17-beta.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1004.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-466]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-466]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-466]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at ia.m.sf.a(SourceFile:74) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at ia.m.G.d(SourceFile:929) ~[ItemsAdder_3.6.4-release-3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-466]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-466]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-466]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
So far I didn't have much time and was unable to reproduce the issue.
I do have an idea what it might be and will let you know when I got a fix. Since this is a severe issue the free version will get the fix too.

**Comment by ShadySt** [comment]
If you need any help in testing or want to experiment yourself, I can give you access to my server panel. You can contact me via discord .orphey (member of your ds community)

**Comment by BoenShi128** [comment]
Indeed, I also encountered this situation. I used customcrafting-spigot-4.16.11, wolfyutils-spigot-4.17-beta.6，ItemsAdder_3.6.4-release-2.

[15:27:50 ERROR]: Could not pass event PluginIntegrationEnableEvent to CustomCrafting v4.16.11
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
        at com.google.common.collect.AbstractMapBasedMultimap$KeySet$1.next(AbstractMapBasedMultimap.java:964) ~[guava-32.1.2-jre.jar:?]
        at me.wolfyscript.customcrafting.handlers.LocalStorageLoader.validatePending(LocalStorageLoader.java:206) ~[plugin-27-customcrafting-spigot-4.16.11.jar:?]
        at me.wolfyscript.customcrafting.handlers.DataHandler.integrationEnable(DataHandler.java:150) ~[plugin-27-customcrafting-spigot-4.16.11.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.wolfyscript.utilities.compatibility.PluginIntegrationAbstract.enable(PluginIntegrationAbstract.java:108) ~[plugin-97-wolfyutils-spigot-4.17-beta.6.jar:?]
        at me.wolfyscript.utilities.compatibility.PluginIntegrationAbstract.markAsDoneLoading(PluginIntegrationAbstract.java:131) ~[plugin-97-wolfyutils-spigot-4.17-beta.6.jar:?]
        at me.wolfyscript.utilities.compatibility.plugins.itemsadder.ItemsAdderImpl.onLoaded(ItemsAdderImpl.java:65) ~[plugin-97-wolfyutils-spigot-4.17-beta.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor252.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at ia.m.sf.a(SourceFile:74) ~[plugin-118-ItemsAdder_3.6.4-release-2.jar:?]
        at ia.m.G.d(SourceFile:929) ~[plugin-118-ItemsAdder_3.6.4-release-2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

Plugin List:
[15:43:02 INFO]: Paper Plugins: (1):
[15:43:02 INFO]:  - HuskHomes
[15:43:02 INFO]: Bukkit Plugins: (32):
[15:43:02 INFO]:  - AuthMe, Bssentials, BungeeTabListPlus, CMI, CMILib, CommandWhitelist, CrossplatForms, CustomCrafting, CustomMachine, FastAsyncWorldEdit
[15:43:02 INFO]:  floodgate, InteractiveBoard, ItemsAdder, KeepChunks, LiteBans, LoneLibs, LuckPerms, MapModCompanion, Multiverse-Core, PlaceholderAPI
[15:43:02 INFO]:  Plan, PlantingAndEating, PlugManX, ProtocolLib, ScreenInMC, SkinsRestorer, spark, Vault, ViaVersion, WolfyUtilities
[15:43:02 INFO]:  WorldGuard, XConomy

**Comment by BoenShi128** [comment]
Indeed, I also encountered this situation. I used customcrafting-spigot-4.16.11, wolfyutils-spigot-4.17-beta.6，ItemsAdder_3.6.4-release-2.

[15:27:50 ERROR]: Could not pass event PluginIntegrationEnableEvent to CustomCrafting v4.16.11
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
        at com.google.common.collect.AbstractMapBasedMultimap$KeySet$1.next(AbstractMapBasedMultimap.java:964) ~[guava-32.1.2-jre.jar:?]
        at me.wolfyscript.customcrafting.handlers.LocalStorageLoader.validatePending(LocalStorageLoader.java:206) ~[plugin-27-customcrafting-spigot-4.16.11.jar:?]
        at me.wolfyscript.customcrafting.handlers.DataHandler.integrationEnable(DataHandler.java:150) ~[plugin-27-customcrafting-spigot-4.16.11.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.wolfyscript.utilities.compatibility.PluginIntegrationAbstract.enable(PluginIntegrationAbstract.java:108) ~[plugin-97-wolfyutils-spigot-4.17-beta.6.jar:?]
        at me.wolfyscript.utilities.compatibility.PluginIntegrationAbstract.markAsDoneLoading(PluginIntegrationAbstract.java:131) ~[plugin-97-wolfyutils-spigot-4.17-beta.6.jar:?]
        at me.wolfyscript.utilities.compatibility.plugins.itemsadder.ItemsAdderImpl.onLoaded(ItemsAdderImpl.java:65) ~[plugin-97-wolfyutils-spigot-4.17-beta.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor252.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at ia.m.sf.a(SourceFile:74) ~[plugin-118-ItemsAdder_3.6.4-release-2.jar:?]
        at ia.m.G.d(SourceFile:929) ~[plugin-118-ItemsAdder_3.6.4-release-2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

Plugin List:
[15:43:02 INFO]: Paper Plugins: (1):
[15:43:02 INFO]:  - HuskHomes
[15:43:02 INFO]: Bukkit Plugins: (32):
[15:43:02 INFO]:  - AuthMe, Bssentials, BungeeTabListPlus, CMI, CMILib, CommandWhitelist, CrossplatForms, CustomCrafting, CustomMachine, FastAsyncWorldEdit
[15:43:02 INFO]:  floodgate, InteractiveBoard, ItemsAdder, KeepChunks, LiteBans, LoneLibs, LuckPerms, MapModCompanion, Multiverse-Core, PlaceholderAPI
[15:43:02 INFO]:  Plan, PlantingAndEating, PlugManX, ProtocolLib, ScreenInMC, SkinsRestorer, spark, Vault, ViaVersion, WolfyUtilities
[15:43:02 INFO]:  WorldGuard, XConomy

**Comment by Tareyu** [comment]
I have the same problem here with the paid version... I did 1 customcraft with a custom Itemadder item and everything is fine, but not for the second one. When i restart the server i got this error!

Paper-1.21.1-74
customcrafting-spigot-4.17-beta.5
wolfyutils-spigot-4.17-beta.7
ItemsAdder_4.0.2-beta-release-10
LoneLibs_1.0.58

`[16:32:34 INFO]: [WolfyUtilities] Enabled plugin integration for ItemsAdder
[16:32:34 ERROR]: Could not pass event PluginIntegrationEnableEvent to CustomCrafting v4.17-beta.5
java.util.ConcurrentModificationException: null
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
        at com.google.common.collect.AbstractMapBasedMultimap$KeySet$1.next(AbstractMapBasedMultimap.java:964) ~[guava-32.1.2-jre.jar:?]
        at customcrafting-spigot-4.17-beta.5.jar/me.wolfyscript.customcrafting.handlers.LocalStorageLoader.validatePending(LocalStorageLoader.java:213) ~[customcrafting-spigot-4.17-beta.5.jar:?]
        at customcrafting-spigot-4.17-beta.5.jar/me.wolfyscript.customcrafting.handlers.ResourceLoader.runScheduledPluginIntegrations(ResourceLoader.java:108) ~[customcrafting-spigot-4.17-beta.5.jar:?]
        at customcrafting-spigot-4.17-beta.5.jar/me.wolfyscript.customcrafting.handlers.ResourceLoader.schedulePluginIntegration(ResourceLoader.java:98) ~[customcrafting-spigot-4.17-beta.5.jar:?]
        at customcrafting-spigot-4.17-beta.5.jar/me.wolfyscript.customcrafting.handlers.DataHandler.integrationEnable(DataHandler.java:149) ~[customcrafting-spigot-4.17-beta.5.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-74-971a7a5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-74-971a7a5]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-74-971a7a5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at wolfyutils-spigot-4.17-beta.7.jar/me.wolfyscript.utilities.compatibility.PluginIntegrationAbstract.enable(PluginIntegrationAbstract.java:108) ~[wolfyutils-spigot-4.17-beta.7.jar:?]
        at wolfyutils-spigot-4.17-beta.7.jar/me.wolfyscript.utilities.compatibility.PluginIntegrationAbstract.markAsDoneLoading(PluginIntegrationAbstract.java:131) ~[wolfyutils-spigot-4.17-beta.7.jar:?]
        at wolfyutils-spigot-4.17-beta.7.jar/me.wolfyscript.utilities.compatibility.plugins.itemsadder.ItemsAdderImpl.onLoaded(ItemsAdderImpl.java:65) ~[wolfyutils-spigot-4.17-beta.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor268.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-74-971a7a5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-74-971a7a5]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-74-971a7a5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at ItemsAdder_4.0.2-beta-release-10.jar/ia.m.ou.a(SourceFile:74) ~[ItemsAdder_4.0.2-beta-release-10.jar:?]
        at ItemsAdder_4.0.2-beta-release-10.jar/ia.m.G.d(SourceFile:923) ~[ItemsAdder_4.0.2-beta-release-10.jar:?]
        at ItemsAdder_4.0.2-beta-release-10.jar/ia.m.nQ.d(SourceFile:130) ~[ItemsAdder_4.0.2-beta-release-10.jar:?]
        at ItemsAdder_4.0.2-beta-release-10.jar/ia.m.G.a(SourceFile:921) ~[ItemsAdder_4.0.2-beta-release-10.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-74-971a7a5]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-74-971a7a5]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.21.1.jar:1.21.1-74-971a7a5]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-74-971a7a5]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[16:32:34 INFO]: Done (29.200s)! For help, type "help"`
