### ISSUE TITLE
Language preventing plugin load

### ISSUE THREAD

**Issue by Netherhunter945** [WolfyScript/CustomCrafting#379]
### What happened?

The title says it 

### How can the bug be reproduced?

Use this version of the plugin:
https://modrinth.com/plugin/customcrafting/version/4.16.11
Use this version of wolfyutils:
https://modrinth.com/plugin/wolfyutils/version/4.17-beta.4

Load the plugin

### Expected Behaviour?

Loading

### Plugin version

Custom Crafting 4.16.11, WolfyUtilities v4.17-beta.4

### Server software

This server is running Paper version 1.21-66-master@99ae7bb (2024-07-14T13:40:23Z) (Implementing API version 1.21-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21-49-b0ef3ca (MC: 1.21)

### Relevant log output

```shell
[17:56:51 ERROR]: Error occurred while enabling CustomCrafting v4.16.11 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'lang/en_US.json' cannot be found in plugins/.paper-remapped/customcrafting-spigot-4.16.11 (1).jar
        at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:215) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at customcrafting-spigot-4.16.11 (1).jar/me.wolfyscript.customcrafting.handlers.ConfigHandler.loadLang(ConfigHandler.java:138) ~[customcrafting-spigot-4.16.11 (1).jar:?]
        at customcrafting-spigot-4.16.11 (1).jar/me.wolfyscript.customcrafting.handlers.ConfigHandler.load(ConfigHandler.java:67) ~[customcrafting-spigot-4.16.11 (1).jar:?]
        at customcrafting-spigot-4.16.11 (1).jar/me.wolfyscript.customcrafting.CustomCrafting.onEnable(CustomCrafting.java:345) ~[customcrafting-spigot-4.16.11 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at PlugManX-2.4.1.jar/com.rylinaux.plugman.pluginmanager.BukkitPluginManager.enable(BukkitPluginManager.java:85) ~[PlugManX-2.4.1.jar:?]
        at PlugManX-2.4.1.jar/com.rylinaux.plugman.pluginmanager.PaperPluginManager.enable(PaperPluginManager.java:139) ~[PlugManX-2.4.1.jar:?]
        at PlugManX-2.4.1.jar/com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:130) ~[PlugManX-2.4.1.jar:?]
        at PlugManX-2.4.1.jar/com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:94) ~[PlugManX-2.4.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1622) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1309) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[17:56:51 INFO]: [CustomCrafting] Disabling CustomCrafting v4.16.11
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
This error usually means the jar file is corrupted or something else went wrong beforehand.
Are there any errors before the one you posted?

**Comment by Netherhunter945** [comment]
Sorry to bother you for a mistake that wasn't yours, the reason it wasn't working is because Protocollib was installed even though it isn't out for 1.21.
