### ISSUE TITLE
Continuous crashes due to CustomCrafting plugin

### ISSUE THREAD

**Issue by ZacianKing** [WolfyScript/CustomCrafting#398]
### What happened?

Good morning, when a player enters, the server crashes and the logs show the classic paper crash error but it also says that it was caused by a plugin, and while I was reading the logs to understand the thing that triggered the cause of the crashes, The CustomCrafting plugin comes up and gives errors but I don't understand how to fix it...

### How can the bug be reproduced?

I simply see this error when I start the server and when some players join the server, causing it to crash and appear this error

### Expected Behaviour?

I couldn't tell you

### Plugin version

CustomCrafting 4.16.8.5 - WolfyUtils 4.16.13.0

### Server software

Paper 1.16.5

### Relevant log output

```shell
[14:30:57 WARN]: [CustomCrafting] [LOCAL] [Error] Invalid Recipe: "customcrafting:customcrafting/recipe_book": 'void it.unimi.dsi.fastutil.ints.IntList.sort(it.unimi.dsi.fastutil.ints.IntComparator)'
[14:30:57 WARN]: [CustomCrafting] [LOCAL] [Error]   Caused by: 'void it.unimi.dsi.fastutil.ints.IntList.sort(it.unimi.dsi.fastutil.ints.IntComparator)'
[14:30:57 WARN]: [CustomCrafting] ------------------[StackTrace]-------------------
[14:30:57 WARN]: me.wolfyscript.lib.com.fasterxml.jackson.databind.JsonMappingException: 'void it.unimi.dsi.fastutil.ints.IntList.sort(it.unimi.dsi.fastutil.ints.IntComparator)'
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:276)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:627)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:615)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:638)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.impl.MethodProperty.set(MethodProperty.java:185)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.impl.PropertyValue$Regular.assign(PropertyValue.java:60)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:211)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:519)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:220)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:144)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1653)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1668)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.handlers.LocalStorageLoader$NewDataLoader.lambda$loadRecipesInNamespace$0(LocalStorageLoader.java:263)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.handlers.LocalStorageLoader$NamespaceFileVisitor.visitFile(LocalStorageLoader.java:398)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.handlers.LocalStorageLoader$NamespaceFileVisitor.visitFile(LocalStorageLoader.java:386)
[14:30:57 WARN]:        at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
[14:30:57 WARN]:        at java.base/java.nio.file.Files.walkFileTree(Files.java:2876)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.handlers.LocalStorageLoader.readFiles(LocalStorageLoader.java:146)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.handlers.LocalStorageLoader$NewDataLoader.loadRecipesInNamespace(LocalStorageLoader.java:256)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.handlers.LocalStorageLoader$NewDataLoader.load(LocalStorageLoader.java:249)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.handlers.LocalStorageLoader.load(LocalStorageLoader.java:74)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.handlers.ResourceLoader.load(ResourceLoader.java:61)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.handlers.DataHandler.load(DataHandler.java:117)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.commands.cc_subcommands.ReloadSubCommand.onCommand(ReloadSubCommand.java:76)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.commands.IndexCommand.execute(IndexCommand.java:59)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.commands.CommandCC.execute(CommandCC.java:71)
[14:30:57 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:30:57 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[14:30:57 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[14:30:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:30:57 WARN]: Caused by: java.lang.NoSuchMethodError: 'void it.unimi.dsi.fastutil.ints.IntList.sort(it.unimi.dsi.fastutil.ints.IntComparator)'
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.recipes.AbstractRecipeShapeless.setIngredients(AbstractRecipeShapeless.java:126)
[14:30:57 WARN]:        at me.wolfyscript.customcrafting.recipes.AbstractRecipeShapeless.setIngredients(AbstractRecipeShapeless.java:106)
[14:30:57 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:30:57 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[14:30:57 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:30:57 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[14:30:57 WARN]:        at me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.impl.MethodProperty.set(MethodProperty.java:182)
[14:30:57 WARN]:        ... 48 more
[14:30:57 INFO]: [CustomCrafting] [LOCAL] Loaded 142 recipes; Skipped: 1 error/s, 0 already existing
[14:30:57 INFO]: [CustomCrafting] [LOCAL_OLD] Loaded 0 recipes; Skipped: 0 error/s, 0 already existing
[14:30:57 INFO]: [CustomCrafting] [LOCAL_LEGACY] Loaded 0 recipes; Skipped: 0 error/s, 0 already existing
[14:30:57 INFO]: [CustomCrafting] [LOCAL] Loaded 142 recipes
[14:30:57 INFO]: [CustomCrafting] 
[14:30:57 INFO]: [CustomCrafting] Indexing Recipe Book...
[14:30:57 INFO]: [CustomCrafting] Indexed Recipe Book!
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Since 1.16.5 is no longer supported, you should update WolfyUtils to the latest possible version that is still compatible. Which would be [4.16.14.1](https://modrinth.com/plugin/wolfyutils/version/4.16.14.1)  
https://github.com/WolfyScript/CustomCrafting/wiki#installation
